import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import {PagebarProvider} from "@/components/pagebar/PagebarContext";
import Sidebar from "@/components/sidebar/Sidebar";
import Pagebar from "@/components/pagebar/Pagebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PagebarProvider>
          <div className="flex">
            <Sidebar />
            <main className="flex-1 bg-zinc-100">
              {children}
            </main>
            <Pagebar />
          </div>
        </PagebarProvider>
      </body>
    </html>
  );
}
