on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to production
    runs-on: self-hosted
    steps:
    - run: |
        tmux send -t runnerFrontend:pane C-c
        tmux send -t runnerFrontend:pane "cd ~/frontend" ENTER
        tmux send -t runnerFrontend:pane "git pull" ENTER
        tmux send -t runnerFrontend:pane "npm ci" ENTER
        tmux send -t runnerFrontend:pane "npm run build" ENTER
        tmux send -t runnerFrontend:pane "npm run start" ENTER
